version: '3.8'

services:
  postgres-db:
    image: postgres:16
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=janettora
      - POSTGRES_HOST_AUTH_METHOD=trust
    networks:
      - bot-network
    stdin_open: true
    tty: true

  bot:
    container_name: bot
    build:
      context: ./
    networks:
      - bot-network
    depends_on:
      - postgres-db

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge